using System;
using System.Collections.Generic;
using System.IO;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace Win81Layer;

internal static class AppIconOverrides
{
	private static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
	{
		["Microsoft.Office.WINWORD.EXE.15"] = "Word_2013",
		["Microsoft.Office.EXCEL.EXE.15"] = "Excel_2013",
		["Microsoft.Office.POWERPNT.EXE.15"] = "PowerPoint_2013",
		["Microsoft.Office.ONENOTE.EXE.15"] = "OneNote_2013",
		["Microsoft.Office.MSACCESS.EXE.15"] = "Access_2013",
		["Microsoft.Windows.Photos_8wekyb3d8bbwe!App"] = "Photos_Windows_8.1",
		["Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"] = "Calculator_Windows_8.1",
		["Microsoft.WindowsStore_8wekyb3d8bbwe!App"] = "Microsoft_Store_Windows_8.1",
		["windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"] = "PC_Settings_Windows_8.1",
		["microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail"] = "Mail_Windows_8.1",
		["microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar"] = "Calendar_Windows_8.1",
		["Microsoft.BingWeather_8wekyb3d8bbwe!App"] = "Weather_Windows_8.1",
		["Claude_pzs8sxrjxfjjc!Claude"] = "Claude",
		["308046B0AF4A39CB"] = "Firefox",
		["VisualStudio.10dcc039"] = "VisualStudio",
		["Microsoft.VisualStudioCode"] = "VSCode",
		["Microsoft.Windows.Explorer"] = "Explorer_81",
		// Task Manager (taskmgr.exe) is a legacy Win32 app, so the shell assigns it a per-machine
		// AutoGenerated AppID (this is the ID Get-StartApps reports on this box). The all-apps / Start
		// tile keys off it; running windows & pins are covered robustly by ExeTable["taskmgr.exe"] below.
		["Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}"] = "TaskManager_81",
		// Remote Desktop Connection (mstsc.exe). Get-StartApps reports the clean AppID below on this box;
		// ExeTable["mstsc.exe"] covers running windows + pins robustly regardless.
		["Microsoft.Windows.RemoteDesktop"] = "RemoteDesktop_81",
		// Alarms & Clock (future-proof: not installed on this box, but if present its tile/all-apps entry
		// gets the authentic crimson Win8.1 clock). The visible Clock is the built-in LIVE tile (LiveTiles).
		["Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"] = "Clock_81",
		// Notepad (UWP on Win11) + classic notepad.exe covered by ExeTable below. Transparent (no BrandHex).
		["Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"] = "Notepad_81",
		// Control Panel (Get-StartApps reports this clean AppID on this box). Transparent (no BrandHex).
		["Microsoft.Windows.ControlPanel"] = "ControlPanel_81",
		// Command Prompt + Registry Editor — legacy System32 exes; AppsFolder AppId = <KnownFolder GUID>\exe
		// (from Get-StartApps). ExeTable below covers running windows + pins robustly. Both transparent (no BrandHex).
		["{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\cmd.exe"] = "Cmd_81",
		["{F38BF404-1D43-42F2-9305-67DE0B28FC23}\\regedit.exe"] = "Registry_81",
		["{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe"] = "PowerShell_81",
		// Paint — modern Win11 Paint is a Store app (AUMID below); classic mspaint.exe is covered by ExeTable. Colourful
		// palette logo -> NO BrandHex (transparent tile, logo shows full-size like Firefox / VSCode).
		["Microsoft.Paint_8wekyb3d8bbwe!App"] = "Paint_81",
		// Windows Terminal — Store app AUMID (+ WindowsTerminal.exe / wt.exe via ExeTable cover running windows + pins).
		// Self-contained window graphic -> NO BrandHex (transparent tile, like cmd / powershell).
		["Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"] = "Terminal_81"
	};

	private static readonly Dictionary<string, string> ExeTable = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
	{
		["winword.exe"] = "Word_2013",
		["excel.exe"] = "Excel_2013",
		["powerpnt.exe"] = "PowerPoint_2013",
		["onenote.exe"] = "OneNote_2013",
		["msaccess.exe"] = "Access_2013",
		["onedrive.exe"] = "OneDrive_Windows_8.1",
		["firefox.exe"] = "Firefox",
		["devenv.exe"] = "VisualStudio",
		["code.exe"] = "VSCode",
		// taskmgr.exe is a dedicated single-purpose exe (never a shared host), so keying it by exe filename is
		// safe and covers running Task Manager windows + any taskbar pin. (Do NOT add explorer.exe here — it hosts
		// Control Panel / This PC too; the File Explorer icon is applied by Aumid instead, see TaskbarPins import.)
		["taskmgr.exe"] = "TaskManager_81",
		["mstsc.exe"] = "RemoteDesktop_81",
		["notepad.exe"] = "Notepad_81",
		["cmd.exe"] = "Cmd_81",
		["regedit.exe"] = "Registry_81",
		["powershell.exe"] = "PowerShell_81",
		["mspaint.exe"] = "Paint_81",
		["WindowsTerminal.exe"] = "Terminal_81",
		["wt.exe"] = "Terminal_81"
	};

	private static readonly Dictionary<string, string> BrandHex = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
	{
		["Word_2013"] = "#2B579A",
		["Excel_2013"] = "#217346",
		["PowerPoint_2013"] = "#B7472A",
		["OneNote_2013"] = "#80397B",
		["Access_2013"] = "#A4373A",
		["Photos_Windows_8.1"] = "#008399",
		["Calculator_Windows_8.1"] = "#007500",
		["Microsoft_Store_Windows_8.1"] = "#009B00",
		// Settings / Calendar / Weather colours taken verbatim from the authentic Win8.1 SVGs the user supplied.
		["PC_Settings_Windows_8.1"] = "#5132AA",
		["Calendar_Windows_8.1"] = "#5132AA",
		["Mail_Windows_8.1"] = "#008299",
		["OneDrive_Windows_8.1"] = "#094AB1",
		["Weather_Windows_8.1"] = "#2671EC",
		["Claude"] = "#181818",
		["RemoteDesktop_81"] = "#DBAD00",
		["Clock_81"] = "#AC193D"
		// Explorer_81 has NO BrandHex again (2026-09-05): the user's yellow File Explorer folder is self-contained
		// colourful art that must show WHOLE on a transparent tile, not boxed in cyan (was #04AEDA = the old cyan flat icon).
		// Firefox / VisualStudio / VSCode intentionally have NO BrandHex -> transparent tile (the original colour
		// logo shows full-size with no background box). Cmd_81 / Registry_81 / Paint_81 / Terminal_81 are transparent too.
	};

	private static readonly object _gate = new object();

	private static readonly Dictionary<string, ImageSource?> _cache = new Dictionary<string, ImageSource>(StringComparer.OrdinalIgnoreCase);

	private static readonly Dictionary<string, Brush?> _brushCache = new Dictionary<string, Brush>(StringComparer.OrdinalIgnoreCase);

	private static string BundledDir => Path.Combine(AppContext.BaseDirectory, "Assets", "Win81Icons", "uwp");

	internal static ImageSource? TryGet(AppEntry e)
	{
		return FromKey((!string.IsNullOrEmpty(e.AppId)) ? e.AppId : StripAppsFolder(e.LaunchPath), small: false);
	}

	internal static bool Has(AppEntry e)
	{
		return AssetFor(e) != null;
	}

	private static string? AssetFor(AppEntry e)
	{
		string key = ((!string.IsNullOrEmpty(e.AppId)) ? e.AppId : StripAppsFolder(e.LaunchPath))?.Trim();
		string a;
		return (!string.IsNullOrEmpty(key) && Table.TryGetValue(key, out a)) ? a : null;
	}

	internal static Brush? BrandBrush(AppEntry e)
	{
		string asset = AssetFor(e);
		if (asset == null || !BrandHex.TryGetValue(asset, out string hex))
		{
			return null;
		}
		lock (_gate)
		{
			if (_brushCache.TryGetValue(asset, out Brush cached))
			{
				return cached;
			}
			Brush b = null;
			try
			{
				Color c = (Color)ColorConverter.ConvertFromString(hex);
				b = new SolidColorBrush(c);
				((Freezable)b).Freeze();
			}
			catch
			{
			}
			_brushCache[asset] = b;
			return b;
		}
	}

	internal static ImageSource? Resolve(PinnedApp p)
	{
		if (!string.IsNullOrEmpty(p.Aumid))
		{
			ImageSource byExplicit = FromKey(p.Aumid, small: true);
			if (byExplicit != null)
			{
				return byExplicit;
			}
		}
		ImageSource byAumid = FromKey(StripAppsFolder(p.LaunchPath), small: true);
		if (byAumid != null)
		{
			return byAumid;
		}
		return ResolveByExe(p.ExePath) ?? ResolveByExe(p.LaunchPath);
	}

	internal static ImageSource? ResolveByAumid(string? aumid)
	{
		return FromKey(aumid, small: true);
	}

	// Override lookup by executable filename (ExeTable). Used for RUNNING desktop apps whose windows expose no
	// AppUserModel.ID (e.g. Firefox / devenv / Code) — without this their taskbar button falls through to the native
	// icon. small=true loads the taskbar (_tb) variant.
	internal static ImageSource? ResolveByExe(string? exePath, bool small = true)
	{
		if (string.IsNullOrEmpty(exePath))
		{
			return null;
		}
		try
		{
			string fn = Path.GetFileName(exePath);
			if (!string.IsNullOrEmpty(fn) && ExeTable.TryGetValue(fn, out string asset))
			{
				return Load(asset, small);
			}
		}
		catch
		{
		}
		return null;
	}

	private static ImageSource? FromKey(string? key, bool small)
	{
		if (string.IsNullOrWhiteSpace(key))
		{
			return null;
		}
		string asset;
		return Table.TryGetValue(key.Trim(), out asset) ? Load(asset, small) : null;
	}

	private static string? StripAppsFolder(string? launchPath)
	{
		if (string.IsNullOrEmpty(launchPath))
		{
			return null;
		}
		string result;
		if (!launchPath.StartsWith("shell:AppsFolder\\", StringComparison.OrdinalIgnoreCase))
		{
			result = launchPath;
		}
		else
		{
			int length = "shell:AppsFolder\\".Length;
			result = launchPath.Substring(length, launchPath.Length - length);
		}
		return result;
	}

	private static ImageSource? Load(string asset, bool small)
	{
		lock (_gate)
		{
			string cacheKey = (small ? (asset + "#tb") : asset);
			if (_cache.TryGetValue(cacheKey, out ImageSource cached))
			{
				return cached;
			}
			ImageSource img = null;
			try
			{
				string file = Path.Combine(BundledDir, asset + (small ? "_tb.png" : ".png"));
				if (File.Exists(file))
				{
					BitmapImage bi = new BitmapImage();
					bi.BeginInit();
					bi.UriSource = new Uri(file);
					bi.CacheOption = BitmapCacheOption.OnLoad;
					bi.EndInit();
					((Freezable)bi).Freeze();
					img = bi;
				}
			}
			catch
			{
			}
			if (_cache.Count >= 256) { _cache.Clear(); }
			_cache[cacheKey] = img;
			return img;
		}
	}

	internal static void RefreshAllSurfaces()
	{
		try
		{
			TaskbarWindow.RefreshPinIcons();
		}
		catch
		{
		}
		try
		{
			StartScreen.RefreshAppIcons();
		}
		catch
		{
		}
		try
		{
			StartScreen.RefreshLiveTiles();   // built-in live tiles (Weather/Agenda/Mail/Clock) revert together
		}
		catch
		{
		}
		try
		{
			TaskbarWindow.RaiseTaskbarButtonsChanged();   // re-apply the taskbar notification icon (8.1 vs native glyph)
		}
		catch
		{
		}
	}
}
